"""initial schema

Revision ID: 75aa42690ca9
Revises: 
Create Date: 2026-09-20 11:29:09.683976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75aa42690ca9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('system_meta',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_owner_id'), ['owner_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('parser_mode', sa.String(length=30), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_record_ids_json', sa.Text(), nullable=True),
    sa.Column('error_summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_owner_id'), ['owner_id'], unique=False)

    op.create_table('project_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_types_name'), ['name'], unique=True)

    op.create_table('project_type_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_type_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('standard_performance_cents', sa.BigInteger(), nullable=False),
    sa.Column('default_ratio_bps', sa.Integer(), nullable=True),
    sa.Column('publicity_required', sa.Boolean(), nullable=False),
    sa.Column('collection_stage', sa.String(length=30), nullable=False),
    sa.Column('payout_pattern', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_type_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_type_rules_project_type_id'), ['project_type_id'], unique=False)

    op.create_table('cooperation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('project_type_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('work_status', sa.String(length=30), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('publicity_status', sa.String(length=30), nullable=False),
    sa.Column('publicity_date', sa.Date(), nullable=True),
    sa.Column('advance_received_date', sa.Date(), nullable=True),
    sa.Column('full_received_date', sa.Date(), nullable=True),
    sa.Column('participation_mode', sa.String(length=20), nullable=False),
    sa.Column('my_ratio_bps', sa.Integer(), nullable=True),
    sa.Column('standard_performance_cents', sa.BigInteger(), nullable=True),
    sa.Column('override_standard_cents', sa.BigInteger(), nullable=True),
    sa.Column('manual_due_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_publicity_required', sa.Boolean(), nullable=False),
    sa.Column('snapshot_collection_stage', sa.String(length=30), nullable=False),
    sa.Column('snapshot_payout_pattern', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['project_type_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cooperation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cooperation_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cooperation_records_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cooperation_records_project_type_id'), ['project_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cooperation_records_record_date'), ['record_date'], unique=False)

    op.create_table('payout_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('cooperation_record_id', sa.String(length=36), nullable=False),
    sa.Column('batch_type', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cooperation_record_id'], ['cooperation_records.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_records_cooperation_record_id'), ['cooperation_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_records_owner_id'), ['owner_id'], unique=False)

    op.create_table('performance_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('cooperation_record_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cooperation_record_id'], ['cooperation_records.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_changes_cooperation_record_id'), ['cooperation_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_changes_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_changes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_performance_changes_cooperation_record_id'))

    op.drop_table('performance_changes')
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_records_cooperation_record_id'))

    op.drop_table('payout_records')
    with op.batch_alter_table('cooperation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cooperation_records_record_date'))
        batch_op.drop_index(batch_op.f('ix_cooperation_records_project_type_id'))
        batch_op.drop_index(batch_op.f('ix_cooperation_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_cooperation_records_company_id'))

    op.drop_table('cooperation_records')
    with op.batch_alter_table('project_type_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_type_rules_project_type_id'))

    op.drop_table('project_type_rules')
    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_types_name'))

    op.drop_table('project_types')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_owner_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_owner_id'))
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))

    op.drop_table('companies')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    op.drop_table('system_meta')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
